# Handling Reading
safe                : false
strict_front_matter : false

# Filtering Content
show_drafts         : false
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : [jekyll-paginate]

# Conversion
markdown            : kramdown
highlighter         : rouge

# Serving
port                : 4000
host                : 127.0.0.1
baseurl             : ""
url                 : http://www.theryjo.com

# Permalinks
permalink           : pretty

# Outputting
timezone            : America/Los_Angeles

quiet               : false
verbose             : false
defaults            : []

kramdown:
  show_warnings     : false

# Plugins
paginate            : 5

# Custom
title            : Ryjo
tagline          : 'Software Developer'
description      : 'LA based software developer'
version          : 0.1
author:
  name           : 'Ryan Jones'
  url            : https://twitter.com/TheRyjo
twitter_username : TheRyjo
github_username  : TheRyjo

# Front matter defaults
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default"

